# Generated by Django 3.0.3 on 2020-02-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('emo', models.CharField(max_length=20)),
                ('od', models.CharField(max_length=20)),
                ('intention', models.CharField(max_length=20)),
                ('personality', models.CharField(max_length=20)),
                ('act', models.CharField(max_length=20)),
                ('word', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('word', models.CharField(max_length=30)),
                ('c_type', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('level', models.IntegerField(null=True)),
            ],
        ),
    ]
