# Generated by Django 3.0.3 on 2020-02-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField(max_length=10)),
                ('y', models.IntegerField(max_length=10)),
                ('word', models.CharField(max_length=30)),
            ],
        ),
    ]
