# Generated by Django 3.0.3 on 2020-02-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowApp', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='y',
            field=models.IntegerField(),
        ),
    ]
