# Generated by Django 3.0.3 on 2020-02-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowApp', '0003_auto_20200212_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='c_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
