# Generated by Django 3.0.3 on 2020-02-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrowApp', '0004_auto_20200219_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
